### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by PeterMitrano** [PeterMitrano/my_cookbook_recipes#1]
- [X] Define a JSON spec for my recipes
- [ ] create more example recipes and put them in dynamo
- [X] create GET at `/recipes?id=####` 
- [ ] create GET at `/search?keywords=####` 
- [ ] write more tests #
